### PR TITLE
Switch to using parallel-ssh instead of fabric redux

### PR DESCRIPTION
**Pull request by dan-blanchard**
This has all of the commits from #400 plus some more to fix travis and fix some minor issues. I wanted to make changes before I merged it into master, and I wanted to be able to more easily test things on my machine.

### CODE REVIEW

**Comment by dan-blanchard** [comment]
It appears the ssh2-python is currently incompatible with PyPy, so I'm going to hold off on this until ParallelSSH/ssh2-python#16 gets addressed.

**Comment by dan-blanchard** [comment]
ssh2-python has fixed the issue on their end, but still waiting for a new parallel-ssh release with the fix there.

**Comment by tanaysoni** [comment]
@dan-blanchard I'd be happy to have a look. Any pointers to reproduce the cases would be helpful.

**Comment by dan-blanchard** [comment]
This is very close to being ready to merge. I am currently being foiled by ParallelSSH/ssh2-python#51 though.

**Comment by dan-blanchard** [comment]
I've tested this with submitting topologies and running them locally, and it all seems to work now.

**Comment by dan-blanchard** [comment]
Seems like there's still an issue with getting all of the options resolved properly with this branch. A `topology.subprocess.timeout` setting I had in `config.json` was not being applied when deploying with this branch. I'll figure that out next week I guess.

**Comment by kbourgoin** [comment]
Closing as very stale

**Pull request closed without merging**
